version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
