[[language]]
name = "rust"
auto-format = false

[language-server.rust-analyzer]
config = { procMacro = { ignored = { leptos_macro = ["component", "server"] } }, rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--rustfmt"] } }
